// currencyData.ts

export type Currency = {
    country: string;
    currency: string;
    symbol: string;
  };
  
  export const currencies: Record<string, Currency> = {
    "AFN": { country: "Afghanistan", currency: "Afghan Afghani", symbol: "؋" },
    "ALL": { country: "Albania", currency: "Albanian Lek", symbol: "L" },
    "DZD": { country: "Algeria", currency: "Algerian Dinar", symbol: "دج" },
    "AOA": { country: "Angola", currency: "Angolan Kwanza", symbol: "Kz" },
    "ARS": { country: "Argentina", currency: "Argentine Peso", symbol: "$" },
    "AMD": { country: "Armenia", currency: "Armenian Dram", symbol: "֏" },
    "AWG": { country: "Aruba", currency: "Aruban Florin", symbol: "ƒ" },
    "AUD": { country: "Australia", currency: "Australian Dollar", symbol: "A$" },
    "AZN": { country: "Azerbaijan", currency: "Azerbaijani Manat", symbol: "₼" },
    "BSD": { country: "Bahamas", currency: "Bahamian Dollar", symbol: "B$" },
    "BHD": { country: "Bahrain", currency: "Bahraini Dinar", symbol: ".د.ب" },
    "BDT": { country: "Bangladesh", currency: "Bangladeshi Taka", symbol: "৳" },
    "BBD": { country: "Barbados", currency: "Barbadian Dollar", symbol: "Bds$" },
    "BYN": { country: "Belarus", currency: "Belarusian Ruble", symbol: "Br" },
    "BZD": { country: "Belize", currency: "Belize Dollar", symbol: "BZ$" },
    "XOF": { country: "Benin", currency: "West African CFA franc", symbol: "Fr" },
    "BMD": { country: "Bermuda", currency: "Bermudian Dollar", symbol: "BD$" },
    "BTN": { country: "Bhutan", currency: "Bhutanese Ngultrum", symbol: "Nu." },
    "BOB": { country: "Bolivia", currency: "Bolivian Boliviano", symbol: "Bs." },
    "BAM": { country: "Bosnia and Herzegovina", currency: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
    "BWP": { country: "Botswana", currency: "Botswana Pula", symbol: "P" },
    "BRL": { country: "Brazil", currency: "Brazilian Real", symbol: "R$" },
    "BND": { country: "Brunei", currency: "Brunei Dollar", symbol: "B$" },
    "BGN": { country: "Bulgaria", currency: "Bulgarian Lev", symbol: "лв" },
    "BIF": { country: "Burundi", currency: "Burundian Franc", symbol: "FBu" },
    "KHR": { country: "Cambodia", currency: "Cambodian Riel", symbol: "៛" },
    "CAD": { country: "Canada", currency: "Canadian Dollar", symbol: "C$" },
    "CVE": { country: "Cape Verde", currency: "Cape Verdean Escudo", symbol: "$" },
    "KYD": { country: "Cayman Islands", currency: "Cayman Islands Dollar", symbol: "CI$" },
    "XAF": { country: "Central African Republic", currency: "Central African CFA franc", symbol: "Fr" },
    "CLP": { country: "Chile", currency: "Chilean Peso", symbol: "$" },
    "CNY": { country: "China", currency: "Chinese Yuan", symbol: "¥" },
    "COP": { country: "Colombia", currency: "Colombian Peso", symbol: "$" },
    "KMF": { country: "Comoros", currency: "Comorian Franc", symbol: "CF" },
    "CDF": { country: "Congo (Kinshasa)", currency: "Congolese Franc", symbol: "FC" },
    "CRC": { country: "Costa Rica", currency: "Costa Rican Colón", symbol: "₡" },
    "HRK": { country: "Croatia", currency: "Croatian Kuna", symbol: "kn" },
    "CUP": { country: "Cuba", currency: "Cuban Peso", symbol: "$" },
    "CZK": { country: "Czech Republic", currency: "Czech Koruna", symbol: "Kč" },
    "DKK": { country: "Denmark", currency: "Danish Krone", symbol: "kr" },
    "DJF": { country: "Djibouti", currency: "Djiboutian Franc", symbol: "Fdj" },
    "DOP": { country: "Dominican Republic", currency: "Dominican Peso", symbol: "RD$" },
    "EGP": { country: "Egypt", currency: "Egyptian Pound", symbol: "E£" },
    "ERN": { country: "Eritrea", currency: "Eritrean Nakfa", symbol: "Nkf" },
    "ETB": { country: "Ethiopia", currency: "Ethiopian Birr", symbol: "Br" },
    "EUR": { country: "Eurozone", currency: "Euro", symbol: "€" },
    "FJD": { country: "Fiji", currency: "Fijian Dollar", symbol: "FJ$" },
    "GMD": { country: "Gambia", currency: "Gambian Dalasi", symbol: "D" },
    "GEL": { country: "Georgia", currency: "Georgian Lari", symbol: "ლ" },
    "GHS": { country: "Ghana", currency: "Ghanaian Cedi", symbol: "GH₵" },
    "GTQ": { country: "Guatemala", currency: "Guatemalan Quetzal", symbol: "Q" },
    "GNF": { country: "Guinea", currency: "Guinean Franc", symbol: "FG" },
    "GYD": { country: "Guyana", currency: "Guyanese Dollar", symbol: "G$" },
    "HTG": { country: "Haiti", currency: "Haitian Gourde", symbol: "G" },
    "HNL": { country: "Honduras", currency: "Honduran Lempira", symbol: "L" },
    "HKD": { country: "Hong Kong", currency: "Hong Kong Dollar", symbol: "HK$" },
    "HUF": { country: "Hungary", currency: "Hungarian Forint", symbol: "Ft" },
    "ISK": { country: "Iceland", currency: "Icelandic Króna", symbol: "kr" },
    "INR": { country: "India", currency: "Indian Rupee", symbol: "₹" },
    "IDR": { country: "Indonesia", currency: "Indonesian Rupiah", symbol: "Rp" },
    "IRR": { country: "Iran", currency: "Iranian Rial", symbol: "﷼" },
    "IQD": { country: "Iraq", currency: "Iraqi Dinar", symbol: "ع.د" },
    "ILS": { country: "Israel", currency: "Israeli New Shekel", symbol: "₪" },
    "JMD": { country: "Jamaica", currency: "Jamaican Dollar", symbol: "J$" },
    "JPY": { country: "Japan", currency: "Japanese Yen", symbol: "¥" },
    "JOD": { country: "Jordan", currency: "Jordanian Dinar", symbol: "د.ا" },
    "KZT": { country: "Kazakhstan", currency: "Kazakhstani Tenge", symbol: "₸" },
    "KES": { country: "Kenya", currency: "Kenyan Shilling", symbol: "KSh" },
    "KWD": { country: "Kuwait", currency: "Kuwaiti Dinar", symbol: "د.ك" },
    "KGS": { country: "Kyrgyzstan", currency: "Kyrgyzstani Som", symbol: "с" },
    "LAK": { country: "Laos", currency: "Lao Kip", symbol: "₭" },
    "LBP": { country: "Lebanon", currency: "Lebanese Pound", symbol: "ل.ل" },
    "LSL": { country: "Lesotho", currency: "Lesotho Loti", symbol: "L" },
    "LRD": { country: "Liberia", currency: "Liberian Dollar", symbol: "L$" },
    "LYD": { country: "Libya", currency: "Libyan Dinar", symbol: "ل.د" },
    "MOP": { country: "Macau", currency: "Macanese Pataca", symbol: "MOP$" },
    "MKD": { country: "Macedonia", currency: "Macedonian Denar", symbol: "ден" },
    "MGA": { country: "Madagascar", currency: "Malagasy Ariary", symbol: "Ar" },
    "MWK": { country: "Malawi", currency: "Malawian Kwacha", symbol: "MK" },
    "MYR": { country: "Malaysia", currency: "Malaysian Ringgit", symbol: "RM" },
    "MVR": { country: "Maldives", currency: "Maldivian Rufiyaa", symbol: "Rf" },
    "MRU": { country: "Mauritania", currency: "Mauritanian Ouguiya", symbol: "UM" },
    "MUR": { country: "Mauritius", currency: "Mauritian Rupee", symbol: "₨" },
    "MXN": { country: "Mexico", currency: "Mexican Peso", symbol: "$" },
    "MDL": { country: "Moldova", currency: "Moldovan Leu", symbol: "L" },
    "MNT": { country: "Mongolia", currency: "Mongolian Tögrög", symbol: "₮" },
    "MAD": { country: "Morocco", currency: "Moroccan Dirham", symbol: "د.م." },
    "MZN": { country: "Mozambique", currency: "Mozambican Metical", symbol: "MT" },
    "MMK": { country: "Myanmar", currency: "Burmese Kyat", symbol: "K" },
    "NAD": { country: "Namibia", currency: "Namibian Dollar", symbol: "N$" },
    "NPR": { country: "Nepal", currency: "Nepalese Rupee", symbol: "₨" },
    "ANG": { country: "Netherlands Antilles", currency: "Netherlands Antillean Guilder", symbol: "ƒ" },
    "NZD": { country: "New Zealand", currency: "New Zealand Dollar", symbol: "NZ$" },
    "NIO": { country: "Nicaragua", currency: "Nicaraguan Córdoba", symbol: "C$" },
    "NGN": { country: "Nigeria", currency: "Nigerian Naira", symbol: "₦" },
    "NOK": { country: "Norway", currency: "Norwegian Krone", symbol: "kr" },
    "OMR": { country: "Oman", currency: "Omani Rial", symbol: "ر.ع." },
    "PKR": { country: "Pakistan", currency: "Pakistani Rupee", symbol: "₨" },
    "PAB": { country: "Panama", currency: "Panamanian Balboa", symbol: "B/." },
    "PGK": { country: "Papua New Guinea", currency: "Papua New Guinean Kina", symbol: "K" },
    "PYG": { country: "Paraguay", currency: "Paraguayan Guaraní", symbol: "₲" },
    "PEN": { country: "Peru", currency: "Peruvian Sol", symbol: "S/" },
    "PHP": { country: "Philippines", currency: "Philippine Peso", symbol: "₱" },
    "PLN": { country: "Poland", currency: "Polish Zloty", symbol: "zł" },
    "QAR": { country: "Qatar", currency: "Qatari Riyal", symbol: "ر.ق" },
    "RON": { country: "Romania", currency: "Romanian Leu", symbol: "lei" },
    "RUB": { country: "Russia", currency: "Russian Ruble", symbol: "₽" },
    "RWF": { country: "Rwanda", currency: "Rwandan Franc", symbol: "FRw" },
    "SHP": { country: "Saint Helena", currency: "Saint Helena Pound", symbol: "£" },
    "WST": { country: "Samoa", currency: "Samoan Tālā", symbol: "T" },
    "STN": { country: "São Tomé and Príncipe", currency: "São Tomé and Príncipe Dobra", symbol: "Db" },
    "SAR": { country: "Saudi Arabia", currency: "Saudi Riyal", symbol: "ر.س" },
    "RSD": { country: "Serbia", currency: "Serbian Dinar", symbol: "дин" },
    "SCR": { country: "Seychelles", currency: "Seychellois Rupee", symbol: "₨" },
    "SLL": { country: "Sierra Leone", currency: "Sierra Leonean Leone", symbol: "Le" },
    "SGD": { country: "Singapore", currency: "Singapore Dollar", symbol: "S$" },
    "SBD": { country: "Solomon Islands", currency: "Solomon Islands Dollar", symbol: "SI$" },
    "SOS": { country: "Somalia", currency: "Somali Shilling", symbol: "Sh" },
    "ZAR": { country: "South Africa", currency: "South African Rand", symbol: "R" },
    "KRW": { country: "South Korea", currency: "South Korean Won", symbol: "₩" },
    "SSP": { country: "South Sudan", currency: "South Sudanese Pound", symbol: "£" },
    "LKR": { country: "Sri Lanka", currency: "Sri Lankan Rupee", symbol: "Rs" },
    "SDG": { country: "Sudan", currency: "Sudanese Pound", symbol: "ج.س." },
    "SRD": { country: "Suriname", currency: "Surinamese Dollar", symbol: "$" },
    "SZL": { country: "Swaziland", currency: "Swazi Lilangeni", symbol: "E" },
    "SEK": { country: "Sweden", currency: "Swedish Krona", symbol: "kr" },
    "CHF": { country: "Switzerland", currency: "Swiss Franc", symbol: "CHF" },
    "SYP": { country: "Syria", currency: "Syrian Pound", symbol: "£" },
    "TWD": { country: "Taiwan", currency: "New Taiwan Dollar", symbol: "NT$" },
    "TJS": { country: "Tajikistan", currency: "Tajikistani Somoni", symbol: "SM" },
    "TZS": { country: "Tanzania", currency: "Tanzanian Shilling", symbol: "TSh" },
    "THB": { country: "Thailand", currency: "Thai Baht", symbol: "฿" },
    "TOP": { country: "Tonga", currency: "Tongan Paʻanga", symbol: "T$" },
    "TTD": { country: "Trinidad and Tobago", currency: "Trinidad and Tobago Dollar", symbol: "TT$" },
    "TND": { country: "Tunisia", currency: "Tunisian Dinar", symbol: "د.ت" },
    "TRY": { country: "Turkey", currency: "Turkish Lira", symbol: "₺" },
    "TMT": { country: "Turkmenistan", currency: "Turkmenistani Manat", symbol: "m" },
    "UGX": { country: "Uganda", currency: "Ugandan Shilling", symbol: "USh" },
    "UAH": { country: "Ukraine", currency: "Ukrainian Hryvnia", symbol: "₴" },
    "AED": { country: "United Arab Emirates", currency: "United Arab Emirates Dirham", symbol: "د.إ" },
    "GBP": { country: "United Kingdom", currency: "British Pound", symbol: "£" },
    "USD": { country: "United States", currency: "United States Dollar", symbol: "$" },
    "UYU": { country: "Uruguay", currency: "Uruguayan Peso", symbol: "$U" },
    "UZS": { country: "Uzbekistan", currency: "Uzbekistani Som", symbol: "сўм" },
    "VUV": { country: "Vanuatu", currency: "Vanuatu Vatu", symbol: "VT" },
    "VEF": { country: "Venezuela", currency: "Venezuelan Bolívar", symbol: "Bs" },
    "VND": { country: "Vietnam", currency: "Vietnamese Đồng", symbol: "₫" },
    "XPF": { country: "Wallis and Futuna", currency: "CFP Franc", symbol: "₣" },
    "YER": { country: "Yemen", currency: "Yemeni Rial", symbol: "﷼" },
    "ZMW": { country: "Zambia", currency: "Zambian Kwacha", symbol: "ZK" },
    "ZWL": { country: "Zimbabwe", currency: "Zimbabwean Dollar", symbol: "Z$" }
  };
  